-- ===========================================================================
-- DEPRECATED — DO NOT APPLY
-- ===========================================================================
--
-- This file is obsolete. It is kept only as a historical record and its
-- contents do NOT match the live database.
--
-- It is wrong in ways that will cause damage if run:
--
--   * It defines public.profiles with a `full_name` column. The live table
--     uses `name`. handle_new_user() inserts (id, email, name, avatar_url,
--     role), so this file's shape is incompatible.
--
--   * It defines its own public.orders / public.order_items from before the
--     order model was reworked. Those definitions predate:
--       - `orders.id` becoming a human-readable TOT-######## text key
--       - row level security on orders, order_items and order_messages
--       - the SECURITY DEFINER RPCs (place_order, set_order_item_status,
--         submit_order_payment, verify_order_payment, schedule_order_delivery,
--         report_order_dispute, resolve_order_dispute)
--       - order-level payment_status / dispute_status and their triggers
--
--   * It has no notifications, notification_preferences or
--     seller_subscriptions tables, and no event triggers.
--
-- Because these CREATE TABLE statements are `IF NOT EXISTS`, running this file
-- against a partially provisioned database silently skips the tables that
-- already exist while still applying whatever else it declares — leaving the
-- database in a state that matches neither this file nor the migrations.
--
-- The source of truth is the ordered migration set:
--
--     supabase/migrations/001_reconcile_catalog.sql
--     supabase/migrations/002_data_model.sql
--     supabase/migrations/003_notifications.sql
--     supabase/migrations/004_analytics.sql
--     supabase/migrations/005_order_payment_fanout.sql
--     supabase/migrations/006_fix_lifecycle_gaps.sql
--     supabase/migrations/007_payment_prompt_and_shipped_type.sql
--     supabase/migrations/008_payment_prompt_on_first_item.sql
--
-- See supabase/MIGRATIONS.md for the apply order, per-step verification
-- queries, and design notes.
--
-- The previous contents of this file remain available in git history:
--
--     git log --follow -- supabase/schema.sql
--     git show 8ebe39f:supabase/schema.sql
