-- ===========================================================================
-- DEPRECATED — DO NOT APPLY
-- ===========================================================================
--
-- This seed file is obsolete and will fail if run.
--
-- It inserts into public.profiles with hardcoded auth user ids:
--
--     11111111-1111-4111-a111-111111111111  Aarav Sharma
--     ... and further fixed UUIDs
--
-- public.profiles.id is a foreign key to auth.users(id). Those users do not
-- exist in a real project, so every INSERT violates the FK constraint and the
-- whole file aborts on the first statement.
--
-- It is also written against the old profiles shape (`full_name`, `phone`),
-- not the current one (`name`, `email`, `avatar_url`, `role`), so even with
-- the users present the column list would not match.
--
-- Local development data is created by the application itself, or by creating
-- a real account and listing a stall through the UI. The order lifecycle is
-- verified by scripts/e2e-order-lifecycle.js, which provisions throwaway
-- accounts against the live project.
--
-- The source of truth for the database is the ordered migration set in
-- supabase/migrations/ — see supabase/MIGRATIONS.md.
--
-- The previous contents of this file remain available in git history:
--
--     git log --follow -- supabase/seed.sql
--     git show 8ebe39f:supabase/seed.sql
